### ISSUE TITLE
add default.json file with the given code

### ISSUE THREAD

**Issue by TtgNoob** [TtgNoob/discord-bot#14]
add default.json file in `json/color`
Now add this given code in `json/color/default.json`
**CODE:**
```json
{
    "color": "Red"
}
```

**Comment by TtgNoob** [comment]
> @TtgNoob can I contribute in this issue

done

**Comment by CodingWithHardik** [comment]
can I also work with this issue

**Comment by TtgNoob** [comment]
> can I also work with this issue

done
