### ISSUE TITLE
Need changes

### ISSUE THREAD

**Issue by TtgNoob** [TtgNoob/discord-bot#31]
change say message command color to `color.color` and add `const color = require('../../json/color/default.json');` at top

**Comment by Hyper-The-Hacker** [comment]
> change say message command color to `color.color` and add `const color = require('../../json/color/default.json');` at top

hey assign me please

**Comment by TtgNoob** [comment]
> > change say message command color to `color.color` and add `const color = require('../../json/color/default.json');` at top
> 
> hey assign me please

done bro you msg to assign too fast

**Comment by Hyper-The-Hacker** [comment]
> > > change say message command color to `color.color` and add `const color = require('../../json/color/default.json');` at top
> > 
> > 
> > hey assign me please
> 
> done bro you msg to assign too fast

lol sorry
