### ISSUE TITLE
message is not sending in channel

### ISSUE THREAD

**Issue by TtgNoob** [TtgNoob/discord-bot#4]
There is a bug in `messageCreate.js` you can't send message fix that

**Comment by beheradibas** [comment]
hi @TtgNoob ,
I would like to work on this

**Comment by beheradibas** [comment]
Can you tell me a bit about how to setup on local dev and test, that way I can check if it working correctly.

**Comment by TtgNoob** [comment]
> Can you tell me a bit about how to setup on local dev and test, that way I can check if it working correctly.

**Hint:** You have to put `!` before one word

**Comment by beheradibas** [comment]
Okay, trying rn.

**Comment by TtgNoob** [comment]
> Okay, trying rn.

**Steps:**
1. Open messageCreate.js file
2. find `message.content.toLowerCase().startsWith(prefixConfig.DefaultPrefix)`
3. replace to `!message.content.toLowerCase().startsWith(prefixConfig.DefaultPrefix)`

**Comment by beheradibas** [comment]
Btw I would like to know details about how should I add the mongodb uri, any syntax or wiki would be really useful for me. 

Learned to add a bot to server which is cool. thanks for the opportunity.

But for mongo uri don't I need to have have the specific format database and also uri to that database ?
