### ISSUE TITLE
add ping.js file using the given instructions 

### ISSUE THREAD

**Issue by TtgNoob** [TtgNoob/discord-bot#9]
make new folder named with `Utility` in `MessageCommand` and then create a file named `ping.js`
it should look like `MessageCommand/Utility/ping.js`
then copy the code from `messageExample.js`
1. Edit the name with ping
2. No aliases means `[]` make like this
3. set timeout to 5000
4. change `[]` to `[PermissionFlagsBits.ViewChannel, PermissionFlagsBits.SendMessages, PermissionFlagsBits.EmbedLinks]` in `clientPermissions`
5. change `[]` to `[PermissionFlagsBits.ViewChannel, PermissionFlagsBits.SendMessages]` in `userPermissions`
6. edit about to `Check My Ping!`
7. edit usage to ``${prefix.DefaultPrefix}ping``
8. then add code given below
9. change - `const { Message, Client } = require("discord.js");` to + `const { Message, Client, PermissionFlagsBits, EmbedBuilder } = require("discord.js");
const math = require('mathjs');
const color = require('../../json/color/default.json');
const pingchecks = require('../../schemas/pingchecks')
const prefix = require('../../json/prefix/PrefixList.json')`
**Code:**
```javascript
const send1st = await message.channel.send({ content: `Pinging ...`})
        new pingchecks({
            ping: 0,
            user: message.author.id
        }).save().then((db) => {
            pingchecks.find({ user: message.author.id }).deleteMany().exec();
            var a1 = [...client.ws.shards.values()].map(x => x.ping)
            const ping = new EmbedBuilder()
            .setDescription(`\`\`\`nim\nGateway Ping : : ${a1[message.guild.shardId]}ms\nREST Ping : : ${math.subtract(send1st.createdTimestamp, message.createdTimestamp)}ms\nDatabase Ping : : ${db.ping}ms\`\`\``)
            .setColor(color.color)
            .setAuthor({ iconURL: client.user.avatarURL(), name: `🏓 Pong`})
            send1st.edit({ content: null, embeds: [ping] })
        })```

**Comment by CodingWithHardik** [comment]
hey can you please assign me with this issue
